name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: oos-app-file-explorer

      - name: Minify Action
        uses: dra1ex/minify-action@v1.0.3

      - name: Create files directory
        run: mkdir ${{ github.workspace }}/oos-app-file-explorer/files

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: oos-app-file-explorer
          path: ${{ github.workspace }}/oos-app-file-explorer
