name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: oos-app-file-explorer

      - name: Minify-JS Action
        uses: jossydevers/minify-js@v1.0.0
        with:
          directory: $GITHUB_WORKSPACE/oos-app-file-explorer

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: oos-app-file-explorer
          path: $GITHUB_WORKSPACE/oos-app-file-explorer
